# Generated by Django 5.1.6 on 2025-03-26 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0005_question_voter_alter_question_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="voter",
            field=models.ManyToManyField(
                related_name="voter_Answer", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
